[tool.poetry]
name = "sfn_workflow_client"
version = "1.1.1"
description = "Enhanced, asyncio-compatible client for AWS Step Functions."
authors = ["Jonathan Drake <jdrake@narrativescience.com>"]
license = "BSD-3-Clause"
readme = "README.md"
homepage = "https://github.com/NarrativeScience/sfn-workflow-client"
repository = "https://github.com/NarrativeScience/sfn-workflow-client"

[tool.poetry.dependencies]
aenum = "^3.1.11"
arrow = "^1.2.3"
backoff = "^2.2.1"
boto3 = "^1.24.59"
python = ">=3.7,<4"

[tool.poetry.dev-dependencies]
pre-commit = "^2.18.1"
pytest = "^7.1.2"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
# These rules should conform to flake8-import-order's google import order style
# and black's styling rules
# If adding a new package to this list, please make sure to update the flake8 config as well
atomic = true
combine_as_imports = true
default_section = "THIRDPARTY"
force_sort_within_sections = true
include_trailing_comma = true
known_first_party = [
    "sfn_workflow_client"
]
line_length = 88
multi_line_output = 3
no_lines_before = "LOCALFOLDER"
order_by_type = false
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER"
]
skip = "__init__.py"

[tool.mypy]
mypy_path = "sfn_worflow_client"
ignore_missing_imports = true
allow_redefinition = true
no_strict_optional = true
follow_imports = "silent"
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_unreachable = true

[tool.pydocstyle]
convention = "google"
add-select = ["D413"]
add-ignore = ["D202", "D205", "D415"]

[tool.codespell]
context = 1
quiet-level = 3
ignore-words-list = [
    "mape"
]
