[tool.poetry]
name = "dm-cli"
version = "0.1.0"
description = "CLI tool for the development framework"
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "app" }
]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.3"
pyperclip = "^1.8.2"
dmss-api = "^0.3.21"
requests = "^2.28.1"
progress = "^1.6"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
flake8 = "^5.0.4"
bandit = "^1.7.4"
pytest = "^7.1.3"
black = "^22.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
