[tool.poetry]
name = "easy-pysy"
version = "0.0.3"
description = ""
authors = ["Pierre Merienne <pierre.merienne@gmail.com>"]
packages = [
    { include = "easy_pysi" },
]


[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.6.1"
fastapi = "^0.85.0"
uvicorn = {extras = ["standard"], version = "^0.18.3"}
toml = "^0.10.2"
requests = "^2.28.0"
pendulum = "^2.1.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
mypy = "^0.971"

[tool.poetry.scripts]
ez = 'easy_pysi.console:main'

[tool.mypy]
python_version = 3.9

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)4s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"