[tool.poetry]
name = "py-book-util"
version = "0.1.3"
description = ""
authors = ["\"Richard.Tang\" <tang_can@qq.com>"]
readme = "README.md"
packages = [{include = "py_book_util"}]

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
behave = "^1.2.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
