[project]
name = "macal"
version = "4.0.63"
authors = [
  { name="Marco Caspers", email="marco.caspers@westcon.com" },
]
description = "A proprietary scripting language"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "unidecode",
]

[project.urls]
"Homepage" = "https://github.com/Sama-Developer/macal"