[tool.poetry]
name = "didyoumean-nhannht"
version = "0.1.3"
description = ""
authors = ["nhanclassroom <nhanclassroom@gmail.com>"]
readme = "README.md"
packages = [{include = "didyoumean_nhannht"}]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
[tool.poetry.scripts]
didyoumean = "didyoumean_nhannht.main:main"