[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "iot_gh"
version = "3.0.0"
authors = [
  { name="K2Controls", email="keith@k2controls.net" },
]
description = "IoT Greenhouse service"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/k2controls/iot_gh"
"Bug Tracker" = "https://github.com/k2controls/iot_gh/issues"