[tool.poetry]
name = "sonusai"
version = "0.8.5"
description = "Framework for building deep neural network models for sound, speech, and voice AI"
authors = ["Chris Eddington <chris@aaware.com>", "Jason Calderwood <jason@aaware.com>"]
maintainers = ["Chris Eddington <chris@aaware.com>", "Jason Calderwood <jason@aaware.com>"]
homepage = "https://aaware.com"
license = "GPL-3.0-only"
readme = "README.rst"
include = ["sonusai/data/genmixdb.yml", "sonusai/data/whitenoise.wav"]

[tool.poetry.scripts]
sonusai = 'sonusai.main:main'
aawscd_probwrite = 'sonusai.aawscd_probwrite:main'

[tool.poetry.dependencies]
PyYAML = "^6.0"
dataclasses-json = "^0.5.7"
docopt = "^0.6"
h5py = ">=2.10.0,<2.11.0"
#h5py = ">=3.1.0,<3.2.0"
#h5py = "^3"
keras-tuner = "^1.1.3"
matplotlib = "^3.5"
paho-mqtt = "^1.6.1"
pandas = "^1"
protobuf = "^3.20.1"
pyaaware = "^1.3.20"
python = ">=3.8,<3.11"
scikit-learn = "==1.0.*"
sh = "^1.14.2"
sklearn = "^0.0"
sox = "^1"
tensorflow = "==2.4.*"
tensorflow_addons = "==0.12.1"
tf2onnx = "^1"
tqdm = "^4.62"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
