[tool.poetry]
name = "thresult"
version = "0.9.13"
description = "TangledHub Result"
license = "BSD 3-clause"
authors = ["TangledHub <info@tangledgroup.com>"]
readme = "README.md"
repository = "https://gitlab.com/tangledlabs/thresult"
keywords = ["tangled", "tangledgroup", "tangledhub", "tangledlabs", "tangledcloud", "thresult"]
# Classifiers reference: https://pypi.org/classifiers/
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
packages = [{ include = "thresult" }]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
# pytest = "^6.2.5"
# coverage ="^6.2"

# [tool.poetry.scripts]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
