[tool.poetry]
name = "kilroy-face-py-shared"
version = "0.5.0"
description = "shared code for kilroy face SDKs in Python ü§ù"
readme = "README.md"
authors = ["kilroy <kilroymail@pm.me>"]
classifiers = ["License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"]
repository = "https://github.com/kilroybot/kilroy-face-py-shared"
documentation = "https://kilroybot.github.io/kilroy-face-py-shared"

[tool.poetry.dependencies]
python = "^3.9"
betterproto = { version = "^2.0.0b5", allow-prereleases = true }
pydantic = "^1.9"
pyhumps = "^3.7"
jsonschema = "^4.7"

# dev

# test
pytest = { version = "^7.0", optional = true }

[tool.poetry.extras]
# need to do it that way until poetry supports dependency groups: https://github.com/python-poetry/poetry/issues/1644
dev = ["pytest"]
test = ["pytest"]

[build-system]
# this should be there, see https://python-poetry.org/docs/pyproject/#poetry-and-pep-517
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
