[tool.poetry]
name = "timetable-cli"
version = "0.7.0"
description = ""
authors = ["0djentd"]
readme = "README.md"
packages = [{include = "timetable_cli"}]

[tool.poetry.scripts]
timetable-cli = "timetable_cli.cli:commands"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
rich = "^12.6.0"
appdirs = "^1.4.4"


[tool.poetry.group.dev.dependencies]
bumpversion = "^0.7.0"
pytest = "^7.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
