[tool.poetry]
name = "dop-library-dinigo"
version = "0.1.0"
description = "This package contains all the utils and functions that are used in the DOP framework."
authors = ["Daniel IÃ±igo <daniel.inigo@datatonic.com>"]
readme = "README.md"
packages = [
    { include = "dop_library" },
]

[tool.poetry.dependencies]
python = "^3.7"
apache-airflow-providers-google = "^6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
