[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "komputee"
version = "0.0.6"
authors = []
description = "Data Dashboards with FastAPI"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "pydantic",
    "fastapi"
]

[project.urls]
"Homepage" = "https://komputee.com/product"