[tool.poetry]
name = "bluetarget"
version = "0.1.9"
description = "Deploy, monitor and explain your machine learning models"
authors = ["Sergio Kaz <sergio@bluetarget.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
click = "8.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
