[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyConfObj"
version = "0.1.3"
authors = [
  { name="Otger Ballester", email="otger@ifae.es" },
]
description = "A way to define configuration files through classes, save it and load configuration from json/yaml"
readme = "readme.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/otger/pyConfObject"
"Bug Tracker" = "https://github.com/otger/pyConfObject/issues"