[tool.poetry]
name = "merge-config"
version = "0.3.0"
description = ""
authors = ["Barath Kumar <barath@mergedup.com>"]

[tool.poetry.dependencies]
python = "^3.9"
python-dotenv = "^0.21.0"
PyYAML = "^6.0"
deepmerge = "^1.0.1"
flatten-dict = "^0.4.2"
pydantic = "^1.10.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
yapf = "^0.32.0"
poethepoet = "^0.13.1"
pytest-sugar = "^0.9.5"
pytest-watch = "^4.2.0"
pyfakefs = "^5.0.0"
moto = "^4.0.7"


[tool.poetry.group.aws.dependencies]
boto3 = "^1.24.93"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
start = "poetry run python src/main.py"
watch = "ptw --clear"
test = "env PYTHONPATH=.:src/ pytest"