[build-system]
requires = [
    "setuptools>=63.4.1",
    "setuptools_scm>=7.0.5"
]
build-backend = "setuptools.build_meta"

[project]
name = "suntranslator"
# version = "0.0.1"
description = "A program to convert text into the Sun language"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fpdf2",
]
authors = [
    { name="Carl Head", email="chead@linuxmail.org" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dynamic = ["version"]

# [project.urls]
# "Homepage" = ""
# "Bug Trackers" = ""

[tool.setuptools_scm]
# write_to = "_version.py"

[project.gui-scripts]
suntranslator = "suntranslator:main"
