[tool.poetry]
name = "helpbutton"
version = "1.0.5"
description = ""
authors = ["Sad_Cat0326"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
discord = "^2.0.0"
typing = "^3.7.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
